#!/bin/bash
#Ejemplo de scanner de puertos
#obtenido de pentestlab.wordpress.com
#Parametros
host=$1
firstport=$2
lastport=$3

#Funcion para escanear puertos
funcion portscan {
	for((counter=$firstport; counter<=$lastport; counter++)) do 
		(echo >/dev/tcp/$host/$counter) > /dev/null 2>&1 | && echo "$counter open"
	done
}
#llamada a la funcion 
portscan
